apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: apache-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: apache
        image: XXX
        - containerPort: 8080
        volumeMounts:
        - name: vol
          mountPath: /var/www/html
      volumes:
        - name: vol
          configMap:
            name: cm
