apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache-test
  labels:
    app: app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
